### ISSUE TITLE
Nice work but license is an issue...

### ISSUE THREAD

**Issue by dotMorten** [mathias13/NTRIP#1]
Nice work on your RTCM and NTRIP repos. I had started building it myself. Got very excited about your work until I saw that it's all released under GPL. Have you considered changing it to MIT or Apache so other people can actually use it too?

**Comment by mathias13** [comment]
What's the problem with GPL? Why not work on the same repository?

**Comment by dotMorten** [comment]
GPL is extremely prohibitive. It forces ALL parts of a project using your code to also be released under GPL. It's pretty much impossible and hardly anyone would be willing to relicense all other components just to use this library (and keep in mind you rarely own all the other 3rd party components of an app). I would suggest MIT or Apache licenses instead, since these are much more permissive.

**Comment by mathias13** [comment]
What plans do you have for it? One issue is that Dotspatial http://dotspatial.codeplex.com/ uses GPL which has a lot of good stuff that i might use. You have to remember that this library is far from complete.

**Comment by dotMorten** [comment]
dotspatial uses LGPL not GPL. It's a little less restrictive, so slightly better, but still considered somewhat evil.

Anyway, wouldn't it be better to design this library to integrate with other libraries well, rather than pulling in functionality from other libraries? Ie, keep this library focused on NTRIP only.
I'm aware it's far from done, and I would love to contribute, but *GPL licenses is out of the question for me (and for A LOT of other people) - I'd rather build my own licensed under MIT or Apache instead.

Btw, check out my similar library for NMEA: http://www.github.com/dotMorten/nmeaparser

**Comment by mathias13** [comment]
Could you briefly describe the difference between MIT and Apache.

**Comment by mathias13** [comment]
I'm willling to change the license if you are still interested to help?
